{
 "title": "PruneLM - Iterative Pruning Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "Model Name",
    "query": {
     "query": "label_values(prune_lm_pruned_model_total{pruning_type=~\"iterative\"}, model_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pruning Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Original Model Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_model_size{model_name=\"original\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Pruned Model Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_model_size{model_name=~\"$model_name\", pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Reduced Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(prune_lm_model_size{model_name=\"original\",pruning_type=\"iterative\"} - ignoring(model_name)prune_lm_model_size{model_name=~\"$model_name\", pruning_type=\"iterative\"})"
    }
   ]
  },
  {
   "title": "Compression Percentage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((prune_lm_model_size{model_name=~\"$model_name\", pruning_type=\"iterative\"} / ignoring(model_name)prune_lm_model_size{model_name=~\"original\", pruning_type=\"iterative\"}) * 100)"
    }
   ]
  },
  {
   "title": "Original Model Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_parameters{model_name=\"original\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Pruned Model Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_parameters{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Dropped Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_parameters{model_name=\"original\",pruning_type=\"iterative\"} - ignoring(model_name)prune_lm_total_parameters{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Validation Perplexity (Original Model)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_valid_ppl{model_name=\"original\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Validation Perplexity (Pruned Model)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_valid_ppl_final{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "description": "Show the perplexity difference between pruned model and the original model, If the difference < 0 (less than 0) then that's mean pruned model perform worse than the original model.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_valid_ppl{model_name=\"original\",pruning_type=\"iterative\"} - ignoring(model_name)prune_lm_valid_ppl_final{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Test Perplexity (Original Model)",
   "type": "stat",
   "description": "The perplexity of the Original Language Model with the test dataset.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_test_ppl{model_name=\"original\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Test Perplexity (Pruned Model)",
   "type": "stat",
   "description": "The perplexity of the Compressed (Pruned) Language Model with the test dataset.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_test_ppl{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "description": "Show the perplexity difference between pruned model and the original model (with the testing dataset), If the difference < 0 (less than 0) then that's mean pruned model perform worse than the original model",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_test_ppl{model_name=\"original\",pruning_type=\"iterative\"} - ignoring(model_name)prune_lm_test_ppl{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  { "title": "Training Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Performance on Training Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prune_lm_train_ppl{model_name=~\"$model_name\",pruning_type=\"iterative\"}",
     "legendFormat": "Training Perplexity"
    },
    {
     "expr": "prune_lm_train_loss{model_name=~\"$model_name\",pruning_type=\"iterative\"}",
     "legendFormat": "Training Loss"
    }
   ]
  },
  {
   "title": "Performance on Validation Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prune_lm_valid_ppl{model_name=~\"$model_name\",pruning_type=\"iterative\"}",
     "legendFormat": "Validation Perplexity"
    },
    {
     "expr": "prune_lm_valid_loss{model_name=~\"$model_name\",pruning_type=\"iterative\"}",
     "legendFormat": "Validation Loss"
    }
   ]
  },
  {
   "title": "Training Progress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((prune_lm_last_epoch{model_name=~\"$model_name\",pruning_type=\"iterative\"}) / prune_lm_total_epoch{model_name=\"$model_name\",pruning_type=\"iterative\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Epochs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_epoch{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Last Epoch Finished At",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_last_epoch_finished{model_name=~\"$model_name\",pruning_type=\"iterative\"} * 1000"
    }
   ]
  },
  {
   "title": "Last Epoch Elapsed Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_last_epoch_elapsed{model_name=\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Last Epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_last_epoch{model_name=~\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  },
  {
   "title": "Total Elapsed Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_elapsed_time{model_name=\"$model_name\",pruning_type=\"iterative\"}"
    }
   ]
  }
 ]
}