{
 "title": "PruneLM - Basic Pruning Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "Model Name",
    "query": {
     "query": "label_values(prune_lm_pruned_model_total{pruning_type=~\"basic\"}, model_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Original Model Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_model_size{model_name=\"original\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Pruned Model Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_model_size{model_name=~\"$model_name\", pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Reduced Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(prune_lm_model_size{model_name=\"original\",pruning_type=\"basic\"} - ignoring(model_name)prune_lm_model_size{model_name=~\"$model_name\", pruning_type=\"basic\"})"
    }
   ]
  },
  {
   "title": "Compression Percentage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((prune_lm_model_size{model_name=~\"$model_name\", pruning_type=\"basic\"} / ignoring(model_name)prune_lm_model_size{model_name=~\"original\", pruning_type=\"basic\"}) * 100)"
    }
   ]
  },
  {
   "title": "Original Model Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_parameters{model_name=\"original\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Pruned Model Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_parameters{model_name=~\"$model_name\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Dropped Parameters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_total_parameters{model_name=\"original\",pruning_type=\"basic\"} - ignoring(model_name)prune_lm_total_parameters{model_name=~\"$model_name\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Validation Perplexity (Original Model)",
   "type": "stat",
   "description": "The perplexity of the ***Original Language Model*** with the validation dataset.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_valid_ppl{model_name=\"original\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Validation Perplexity (Pruned Model)",
   "type": "stat",
   "description": "The perplexity of the ***Compressed (Pruned) Language*** Model with the validation dataset.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_valid_ppl{model_name=~\"$model_name\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "description": "Show the perplexity difference between pruned model and the original model, ***If the difference > 0 (greater than 0) then that's mean pruned model performs better than the original model***",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_valid_ppl{model_name=\"original\",pruning_type=\"basic\"} - ignoring(model_name)prune_lm_valid_ppl{model_name=~\"$model_name\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Test Perplexity (Original Model)",
   "type": "stat",
   "description": "The perplexity of the ***Original Language Model*** with the test dataset.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_test_ppl{model_name=\"original\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Test Perplexity (Pruned Model)",
   "type": "stat",
   "description": "The perplexity of the ***Compressed (Pruned) Language*** Model with the test dataset.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_test_ppl{model_name=~\"$model_name\",pruning_type=\"basic\"}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "description": "Show the perplexity difference between pruned model and the original model (with the testing dataset), ***If the difference > 0 (greater than 0) then that's mean pruned model performs better than the original model***",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prune_lm_test_ppl{model_name=\"original\",pruning_type=\"basic\"} - ignoring(model_name)prune_lm_test_ppl{model_name=~\"$model_name\",pruning_type=\"basic\"}"
    }
   ]
  }
 ]
}